@startuml
title Attach Sequence
[-> UE: 0.0988 ms start
UE -> eNodeB: Attach Request
eNodeB -> MME: Attach Request
MME ->]: 0.0993 ms Received
MME -> eNodeB: Attach Successful
eNodeB -> UE: Attach Successful
UE -> eNodeB:  Attach Request from PLMN Search finished successfully
@enduml
